import { SelectProvider } from "./context/SelectContext";
import "./globals.css";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Frontend Mentor | Multi-step form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="./assets/images/favicon-32x32.png"
      ></link>
      <body
        className={`${ubuntu.className}  bg-[#EEF4FB] w-screen h-screen max-md:min-h-[800px] md:flex justify-center md:items-center max-md:px-auto`}
      >
        <SelectProvider>{children}</SelectProvider>
      </body>
    </html>
  );
}
